name: run-tests

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v1

    # Set up C++ build environment
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ make valgrind # Install the necessary dependencies

    # Run make test
    - name: Run make test
      run: |
        make test CXXFLAGS="-fPIC"

    # # Run valgrind for the tests (optional)
    # - name: Run valgrind test
    #   if: matrix.os == 'ubuntu-20.04'
    #   run: |
    #     sudo apt install -y valgrind
    #     make valgrind_test CXXFLAGS="-fPIC"

    # Upload the artifacts (compiled files)
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: compiled-${{ matrix.os }}
        path: .
